### ISSUE TITLE
Multipart first names.

### ISSUE THREAD

**Issue by ar0r** [uchicago-cs/chisubmit#20]
A student whose first name is "Name1 Name2" and last name is "Name3" shows up with "Name2 Name3, Name1" when he shows the members of his team.  It should be "Name3, Name1 Name2".

**Comment by borjasotomayor** [comment]
This is actually not a bug with chisubmit but a bug with Techstaff's LDAP server (which supplies the student's name when they log in with their CNetID). I have reported it to Techstaff a couple of times, and it has yet to be fixed.
